### ISSUE TITLE
windpower: Use 'iconSize: 40, 40, bottom'

### ISSUE THREAD

**Issue by pietervdvn** [seppesantens/MapComplete-Themes#1]
If you use 'bottom', the bottom point will be matched and the pole will stay on the same location on the map

**Comment by seppesantens** [comment]
I've implemented this, although I'm not sure whether the "bottom" really does what was expected

**Comment by pietervdvn** [comment]
Right, up till now 'bottom' never had a space... This should fix it: https://github.com/pietervdvn/MapComplete/commit/ad04dd0abac247c088580848b8c2c541986ab111
