### ISSUE TITLE
windpower: test the new units

### ISSUE THREAD

**Issue by pietervdvn** [seppesantens/MapComplete-Themes#3]
I rolled out a new feature (not in production ATM) to handle units better.

In this feature, you define that some keys should be interpreted with a certain denomination, e.g. as 'length' or as 'power output'. This makes sure that 

- the correct denomination is always added
- the value is in a canonical form (so always with the denomination)
- invalid values (e.g. 'power:generator=yes') will be omitted from the loaded data, forcing to query for this

[The documentation is here](https://github.com/pietervdvn/MapComplete/blob/62244c02c424e70bed7d89881d0e0ca195c2c3e4/Customizations/JSON/LayoutConfigJson.ts#L245) and [here](https://github.com/pietervdvn/MapComplete/blob/feature/units/Customizations/JSON/UnitConfigJson.ts). **If the documentation is unclear or you had to think about the wordings for just a few seconds, please let me know or improve it**

An example is implemented in the [climbing theme](https://github.com/pietervdvn/MapComplete/blob/62244c02c424e70bed7d89881d0e0ca195c2c3e4/assets/themes/climbing/climbing.json#L824)

Please, try this out; let me know if the documentation is unclear. You can test this on [pietervdvn.github.com/mc/units](https://pietervdvn.github.io/mc/feature/units/index.html?userlayout=https://raw.githubusercontent.com/seppesantens/MapComplete-Themes/main/OpenWindPowerMap/OpenWindPowerMap.json#welcome)

**Comment by seppesantens** [comment]
The [wiki](https://wiki.openstreetmap.org/wiki/Climbing#Climbing_sites) seems to suggest that the unit (_m_) should be omitted when adding the value to the climbing:length tag.
For [generator:output:electricity](https://wiki.openstreetmap.org/wiki/Key:generator:output), it says the unit should be added (W / kW / MW / GW) and it even says that "yes" is a valid value for this key. Makes me wonder whether the new units thing can be applied to this key.

**Comment by seppesantens** [comment]
Initial feedback when testing on the climbing theme: https://github.com/pietervdvn/MapComplete/issues/383

**Comment by seppesantens** [comment]
implemented here: https://github.com/seppesantens/MapComplete-Themes/blob/units/OpenWindPowerMap/OpenWindPowerMap.json

**Comment by seppesantens** [comment]
merged into main branch
