### ISSUE TITLE
Push request of the Windpower theme

### ISSUE THREAD

**Issue by pietervdvn** [seppesantens/MapComplete-Themes#4]
As the windpower theme is nice, is nice and fits mapcomplete well, I'd like to have it in MapComplete once it is finished (see #1, #2 and #3).

The steps to do this:

- Checkout the mapcomplete repo. You should have collaborator access, so you don't have to fork
- Create a new branch, create a directory `assets/themes/windpower` and put your theme there
- Run `ts-node scripts/fixtheme assets/themes/windpower/windpower.json`
- Fix the attributions in license.info, and rename (see the script output)
- Open a pull request

**Comment by seppesantens** [comment]
https://github.com/pietervdvn/MapComplete/pull/414
